const lessons = [
  {
    n: 1, source: "6450_slides.pdf", sourcePages: "3-13",
    zh: { title: "Pandas Series 与时间数据", summary: "导入 Pandas/NumPy，创建 Series，使用标签/位置索引，并解析与生成日期时间。",
      outcome: "创建带标签的一维数据，并准确区分 loc/iloc 与日期解析。",
      topics: [["环境与导入", "import pandas as pd；import numpy as np；检查版本。"], ["Series", "从 list、dict 或 scalar 创建带 index、dtype、name 的一维数组。"], ["四种索引", "loc/at 按标签；iloc/iat 按位置；标签切片含末端，位置切片不含末端。"], ["时间数据", "to_datetime 解析日期；date_range 按频率生成 DatetimeIndex。"]],
      demo: `import pandas as pd\n\ns = pd.Series([10, 20, 30], index=["a", "b", "c"], name="points")\nprint(s.loc["b"])\nprint(s.iloc[0:2])\nprint(pd.to_datetime(["2025-07-01", "July 3, 2025"]))`,
      lab: `import pandas as pd\n\ns = pd.Series([12, 18, 25, 9, 31], index=list("pqrst"), name="score")\nprint(s)\nprint("first:", s.iat[0], "last:", s.iat[-1])\nprint("at or above mean:")\nprint(s[s >= s.mean()])`,
      quiz: ["哪一个按位置读取 Series？", ["iloc", "loc", "at"], 0, "iloc/iat 按整数位置；loc/at 按标签。"],
      homework: "创建 5 个带标签的数值；用 iat 取首尾；筛选不低于均值的值；生成 10 个工作日日期。" },
    en: { title: "Pandas Series and Time Data", summary: "Import Pandas/NumPy, create Series, index by label or position, and work with datetimes.",
      outcome: "Build labeled one-dimensional data and distinguish loc/iloc and datetime parsing.",
      topics: [["Setup", "Import pandas as pd and numpy as np; verify versions."], ["Series", "Create a labeled 1D array from a list, dictionary, or scalar."], ["Four indexers", "loc/at use labels; iloc/iat use positions; their slice endpoints differ."], ["Datetime", "Parse values with to_datetime and generate indexes with date_range."]],
      demo: `import pandas as pd\n\ns = pd.Series([10, 20, 30], index=["a", "b", "c"], name="points")\nprint(s.loc["b"])\nprint(s.iloc[0:2])\nprint(pd.to_datetime(["2025-07-01", "July 3, 2025"]))`, lab: `import pandas as pd\n\ns = pd.Series([12, 18, 25, 9, 31], index=list("pqrst"), name="score")\nprint(s)\nprint("first:", s.iat[0], "last:", s.iat[-1])\nprint(s[s >= s.mean()])`,
      quiz: ["Which indexer reads by position?", ["iloc", "loc", "at"], 0, "iloc/iat use integer position; loc/at use labels."], homework: "Create five labeled values, select the endpoints with iat, filter values at or above the mean, and generate ten business dates." }
  },
  {
    n: 2, source: "6450_slides.pdf", sourcePages: "14-37",
    zh: { title: "Pandas DataFrame 数据分析", summary: "构建、检查、筛选、转换、汇总、排序和组合 DataFrame。", outcome: "完成一个从表格构建到筛选、统计与排序的小型分析流程。",
      topics: [["构建与检查", "DataFrame/from_records；shape、columns、info、dtypes、describe。"], ["索引与筛选", "set_index/reset_index/rename；loc/iloc、布尔条件、isin、query。"], ["类型与统计", "astype、to_numeric、category；mean/median/std 与 agg。"], ["转换与组合", "sort_values、map/apply、insert/drop、concat。"]],
      demo: `import pandas as pd\n\ndf = pd.DataFrame({"name":["Alice","Bob","Cathy","Dan"], "age":[24,29,22,31], "city":["NYC","LA","NYC","Chicago"]})\nprint(df[df["age"] >= 25].sort_values("age", ascending=False))\nprint(df.agg({"age":["min","max","mean"]}))`,
      lab: `import pandas as pd\n\ndf = pd.DataFrame({"product":["A","B","C","D"], "price":[10,25,18,32], "city":["NYC","LA","NYC","LA"]})\ndf["price_usd"] = df["price"] * 1.1\nresult = df[df["price_usd"] >= 20].sort_values(["city","price_usd"], ascending=[True,False])\nprint(result)`,
      quiz: ["同时筛选两个条件时应使用什么？", ["& 并给每个条件加括号", "and", "逗号"], 0, "Pandas 布尔 Series 使用 & 或 |，每个比较要加括号。"], homework: "创建 product/price/city 表；选择两列；分别用 loc 与 iloc 取行；增加 price_usd；按城市升序和价格降序排序。" },
    en: { title: "Pandas DataFrame Analysis", summary: "Construct, inspect, filter, transform, aggregate, sort, and combine DataFrames.", outcome: "Complete a small analysis pipeline from table construction through filtering, statistics, and sorting.",
      topics: [["Build and inspect", "DataFrame/from_records; shape, columns, info, dtypes, describe."], ["Index and filter", "set_index/reset_index/rename; loc/iloc, Boolean masks, isin, query."], ["Types and statistics", "astype, to_numeric, category; mean/median/std and agg."], ["Transform and combine", "sort_values, map/apply, insert/drop, concat."]],
      demo: `import pandas as pd\n\ndf = pd.DataFrame({"name":["Alice","Bob","Cathy","Dan"], "age":[24,29,22,31], "city":["NYC","LA","NYC","Chicago"]})\nprint(df[df["age"] >= 25].sort_values("age", ascending=False))\nprint(df.agg({"age":["min","max","mean"]}))`, lab: `import pandas as pd\n\ndf = pd.DataFrame({"product":["A","B","C","D"], "price":[10,25,18,32], "city":["NYC","LA","NYC","LA"]})\ndf["price_usd"] = df["price"] * 1.1\nprint(df[df["price_usd"] >= 20].sort_values(["city","price_usd"], ascending=[True,False]))`,
      quiz: ["How should two Pandas conditions be combined?", ["Use & and parenthesize each comparison", "Use and", "Use a comma"], 0, "Boolean Series use & or | with each comparison parenthesized."], homework: "Build a product/price/city table, select columns and rows with loc/iloc, add price_usd, and sort by city then price." }
  },
  {
    n: 3, source: "Python Control Flow.ppsx", sourcePages: "10-30",
    zh: { title: "条件判断与程序分支", summary: "布尔表达式、缩进、if/elif/else、紧凑 if 与三元表达式。", outcome: "把现实规则写成边界清楚、可测试的分支程序。",
      topics: [["布尔条件", "比较表达式产生 True/False，决定代码块是否运行。"], ["缩进", "Python 用一致的四空格缩进定义代码块。"], ["多分支", "if/elif/else 从上到下选择第一条成立路径。"], ["简洁表达", "简单赋值可用 value_if_true if condition else value_if_false。"]],
      demo: `score = 86\nif score >= 90:\n    grade = "A"\nelif score >= 70:\n    grade = "B"\nelse:\n    grade = "C"\nprint(grade)`, lab: `cents = 87\nquarters = cents // 25\ncents %= 25\ndimes = cents // 10\ncents %= 10\npennies = cents\nprint(quarters, "quarters", dimes, "dimes", pennies, "pennies")`,
      quiz: ["elif 链会执行几条成立分支？", ["第一条成立分支", "所有成立分支", "最后一条成立分支"], 0, "Python 从上到下选择第一条成立分支。"], homework: "写一个包含至少三种结果的分类器，并测试正常值、边界值和异常值。" },
    en: { title: "Conditions and Branching", summary: "Boolean expressions, indentation, if/elif/else, compact if, and conditional expressions.", outcome: "Translate real rules into branches with clear, testable boundaries.", topics: [["Boolean condition", "A comparison produces True or False and controls execution."], ["Indentation", "Python defines blocks with consistent four-space indentation."], ["Multiple branches", "if/elif/else selects the first true path from top to bottom."], ["Concise expression", "Simple assignments can use value_if_true if condition else value_if_false."]], demo: `score = 86\nif score >= 90:\n    grade = "A"\nelif score >= 70:\n    grade = "B"\nelse:\n    grade = "C"\nprint(grade)`, lab: `cents = 87\nquarters = cents // 25\ncents %= 25\ndimes = cents // 10\ncents %= 10\npennies = cents\nprint(quarters, "quarters", dimes, "dimes", pennies, "pennies")`, quiz: ["How many branches of an elif chain run?", ["The first true branch", "Every true branch", "The last true branch"], 0, "Python selects the first true branch from top to bottom."], homework: "Build a classifier with at least three outcomes and test a normal, boundary, and unusual value." }
  },
  {
    n: 4, source: "Python Control Flow.ppsx", sourcePages: "31-92",
    zh: { title: "for、while 与循环控制", summary: "用 for/range 遍历，用 while 重复到条件改变，并用 break/continue 控制循环。", outcome: "选择合适的循环，追踪状态变化，并避免无限循环。",
      topics: [["for 与序列", "逐个处理 iterable 中的元素。"], ["range", "range(start, stop, step) 的 stop 不包含在结果中。"], ["while", "条件为 True 时持续运行；循环体必须推进状态。"], ["循环控制", "break 立即结束；continue 跳到下一轮；可结合 accumulator。"]],
      demo: `total = 0\nfor value in range(2, 11, 2):\n    total += value\n    print(value, total)`, lab: `secret = 7\nguesses = [3, 9, 7, 5]\nfor guess in guesses:\n    if guess == secret:\n        print("found")\n        break\n    if guess < secret:\n        print("too low")\n    else:\n        print("too high")`, quiz: ["range(2, 8, 2) 产生什么？", ["2, 4, 6", "2, 4, 6, 8", "2, 3, 4, 5, 6, 7"], 0, "range 的 stop 是排他的。"], homework: "分别用 for 和 while 完成两个循环任务；至少使用一次 accumulator，并解释 break 或 continue 的作用。" },
    en: { title: "for, while, and Loop Control", summary: "Iterate with for/range, repeat with while, and control loops with break and continue.", outcome: "Choose the right loop, trace changing state, and prevent infinite loops.", topics: [["for and sequences", "Process each item in an iterable."], ["range", "range(start, stop, step) excludes stop."], ["while", "Repeat while a condition is true; the body must advance state."], ["Loop control", "break exits; continue skips to the next iteration; accumulators collect results."]], demo: `total = 0\nfor value in range(2, 11, 2):\n    total += value\n    print(value, total)`, lab: `secret = 7\nguesses = [3, 9, 7, 5]\nfor guess in guesses:\n    if guess == secret:\n        print("found")\n        break\n    print("too low" if guess < secret else "too high")`, quiz: ["What does range(2, 8, 2) produce?", ["2, 4, 6", "2, 4, 6, 8", "2, 3, 4, 5, 6, 7"], 0, "The stop value is excluded."], homework: "Solve one task with for and one with while, use an accumulator, and explain break or continue." }
  },
  {
    n: 5, source: "Python Functions.ppsx", sourcePages: "1-53",
    zh: { title: "定义、调用与返回函数", summary: "用 def 封装任务，区分参数与实参，并用 return 交回可复用结果。", outcome: "把重复逻辑重构为输入明确、输出可测试的函数。", topics: [["定义与调用", "def 创建命名代码块；只有调用时才运行。"], ["参数与实参", "parameter 在定义中命名输入；argument 是调用时传入的值。"], ["return", "return 结束函数并把值交回调用处；不同于 print。"], ["位置参数", "按参数定义的顺序匹配实参。"]], demo: `def add_bonus(score, bonus):\n    return min(score + bonus, 100)\n\nprint(add_bonus(88, 7))`, lab: `def coin_change(cents):\n    quarters = cents // 25\n    cents %= 25\n    dimes = cents // 10\n    pennies = cents % 10\n    return quarters, dimes, pennies\n\nprint(coin_change(87))`, quiz: ["return 与 print 的核心区别是什么？", ["return 交回值，print 只显示", "它们完全相同", "print 会结束函数"], 0, "返回值可以继续计算或保存；打印只是显示。"], homework: "写两个函数；每个至少调用两次；一个函数返回单值，另一个返回多个相关值。" },
    en: { title: "Defining, Calling, and Returning", summary: "Encapsulate tasks with def, distinguish parameters from arguments, and return reusable results.", outcome: "Refactor repeated logic into functions with clear inputs and testable outputs.", topics: [["Define and call", "def creates a named block; it runs only when called."], ["Parameters and arguments", "A parameter names an input; an argument supplies its value."], ["return", "return ends the function and sends a value back; it differs from print."], ["Positional arguments", "Arguments match parameters by definition order."]], demo: `def add_bonus(score, bonus):\n    return min(score + bonus, 100)\n\nprint(add_bonus(88, 7))`, lab: `def coin_change(cents):\n    quarters = cents // 25\n    cents %= 25\n    dimes = cents // 10\n    pennies = cents % 10\n    return quarters, dimes, pennies\n\nprint(coin_change(87))`, quiz: ["What is the key difference between return and print?", ["return sends a value back; print only displays", "They are identical", "print ends the function"], 0, "A returned value can be stored or used in another calculation."], homework: "Write two functions and call each twice; return one value from one function and multiple related values from the other." }
  },
  {
    n: 6, source: "Python Functions.ppsx", sourcePages: "54-107",
    zh: { title: "高级参数、作用域与函数文档", summary: "类型提示、关键字参数、local/global/nonlocal scope、docstring 与函数设计理由。", outcome: "编写接口清楚、可读、带文档且能避免作用域错误的函数。", topics: [["类型提示", "用 name: type 和 -> return_type 说明预期类型，但运行时通常不强制。"], ["关键字参数", "调用时显式写参数名，提高可读性并允许改变顺序。"], ["作用域", "local 在函数内；global 在模块级；nonlocal 指向外层函数变量。"], ["docstring", "函数首行字符串说明 purpose、parameters、return，支持 help()。"]], demo: `def area(width: float, height: float = 1.0) -> float:\n    """Return rectangle area from width and height."""\n    return width * height\n\nprint(area(height=3, width=4))\nprint(area.__doc__)`, lab: `tax_rate = 0.06\n\ndef total_price(price: float, quantity: int = 1) -> float:\n    """Return price with sales tax for a quantity."""\n    subtotal = price * quantity\n    return round(subtotal * (1 + tax_rate), 2)\n\nprint(total_price(12.5, quantity=3))`, quiz: ["类型提示通常会自动阻止错误类型吗？", ["不会，它主要用于说明和工具检查", "总会", "只在 while 中"], 0, "Python 类型提示默认不是运行时强制检查。"], homework: "重写一个旧函数：加入类型提示、默认参数、关键字调用和 docstring；用至少三个测试案例验证。" },
    en: { title: "Advanced Arguments, Scope, and Documentation", summary: "Type hints, keyword arguments, local/global/nonlocal scope, docstrings, and reasons to use functions.", outcome: "Write readable, documented functions with clear interfaces and predictable scope.", topics: [["Type hints", "Use name: type and -> return_type to document expected types; they are usually not enforced at runtime."], ["Keyword arguments", "Name arguments explicitly for clarity and flexible ordering."], ["Scope", "local lives inside a function; global at module level; nonlocal targets an enclosing function."], ["Docstrings", "The first string documents purpose, parameters, and return value for help()."]], demo: `def area(width: float, height: float = 1.0) -> float:\n    """Return rectangle area from width and height."""\n    return width * height\n\nprint(area(height=3, width=4))\nprint(area.__doc__)`, lab: `tax_rate = 0.06\n\ndef total_price(price: float, quantity: int = 1) -> float:\n    """Return price with sales tax for a quantity."""\n    subtotal = price * quantity\n    return round(subtotal * (1 + tax_rate), 2)\n\nprint(total_price(12.5, quantity=3))`, quiz: ["Do type hints normally block wrong types at runtime?", ["No; they mainly document and support tools", "Always", "Only inside while loops"], 0, "Python annotations are not runtime enforcement by default."], homework: "Revise an earlier function with hints, a default, a keyword call, and a docstring; verify it with three test cases." }
  },
  {
    n: 7, source: "Python Structure.ppsx", sourcePages: "1-278",
    zh: { title: "List、2D List 与 Tuple", summary: "创建、访问、修改和遍历 list；用 2D list 表示表格；用 tuple/unpacking 表示固定记录。", outcome: "根据是否需要修改和数据维度选择 list、2D list 或 tuple。", topics: [["List", "有序、可变、允许重复；支持索引、切片、append/insert/remove/pop/sort。"], ["2D List", "列表中包含列表；用 row/column 双索引和 nested loop 处理。"], ["Tuple", "有序、不可变；支持 count/index、拼接和重复。"], ["Unpacking", "把 tuple 元素赋给多个变量；*rest 接收剩余项；函数多返回值本质上可解包。"]], demo: `table = [["Ava", 85], ["Ben", 92], ["Mia", 88]]\nfor name, score in table:\n    print(name, score)\n\nrecord = ("model-a", 0.91, "vision")\nmodel, accuracy, field = record\nprint(model, accuracy, field)`, lab: `scores = [[85, 88, 92], [76, 90, 84]]\nfor r, row in enumerate(scores):\n    print("row", r, "average", sum(row) / len(row))\n\ncolors = ("red", "green", "blue", "gold")\nfirst, *middle, last = colors\nprint(first, middle, last)`, quiz: ["哪种结构创建后不能直接修改元素？", ["tuple", "list", "2D list"], 0, "tuple 是 immutable；需要变化时创建新 tuple。"], homework: "用 2D list 创建至少四行数据并计算统计；再把一行转换成 tuple，演示 unpacking 与 starred unpacking。" },
    en: { title: "Lists, 2D Lists, and Tuples", summary: "Create, access, update, and traverse lists; model tables with 2D lists; represent fixed records with tuples and unpacking.", outcome: "Choose a list, 2D list, or tuple based on mutability and dimensionality.", topics: [["List", "Ordered, mutable, duplicate-friendly; supports indexing, slicing, append/insert/remove/pop/sort."], ["2D list", "Lists inside a list; use row/column indexes and nested loops."], ["Tuple", "Ordered and immutable; supports count/index, concatenation, and repetition."], ["Unpacking", "Assign tuple items to variables; *rest captures extras; multiple returns can be unpacked."]], demo: `table = [["Ava", 85], ["Ben", 92], ["Mia", 88]]\nfor name, score in table:\n    print(name, score)\n\nrecord = ("model-a", 0.91, "vision")\nmodel, accuracy, field = record\nprint(model, accuracy, field)`, lab: `scores = [[85, 88, 92], [76, 90, 84]]\nfor r, row in enumerate(scores):\n    print("row", r, "average", sum(row) / len(row))\n\ncolors = ("red", "green", "blue", "gold")\nfirst, *middle, last = colors\nprint(first, middle, last)`, quiz: ["Which structure does not allow direct item updates?", ["tuple", "list", "2D list"], 0, "Tuples are immutable; create a new tuple when data must change."], homework: "Create four rows in a 2D list and compute a statistic; convert one record to a tuple and demonstrate regular and starred unpacking." }
  },
  {
    n: 8, source: "Python Structure.ppsx", sourcePages: "279-366",
    zh: { title: "Dictionary 与词频项目", summary: "用 key-value 建模，访问、增改、删除和遍历字典，并完成库存与词频项目。", outcome: "把现实关系建模为 dictionary，并构建经过文本预处理的词频统计器。", topics: [["Key-value", "dictionary 有序（现代 Python）、可变、key 唯一；值可重复。"], ["访问与更新", "[]、get、keys/values/items；赋值新增/更新；pop/popitem 删除。"], ["遍历", "直接迭代 key；values() 迭代值；items() 迭代并解包键值对。"], ["词频", "转小写、清理标点、split，再用 get(word, 0)+1 累计。"]], demo: `students = {"Zoe": 99, "Yara": 88, "Diana": 92}\nstudents["Alice"] = 85\nfor name, score in students.items():\n    print(f"{name}: {score}")`, lab: `text = "The quick brown fox jumps over the lazy dog. The dog barked!"\nclean = text.lower()\nfor mark in ".,!?:;":\n    clean = clean.replace(mark, "")\ncounts = {}\nfor word in clean.split():\n    counts[word] = counts.get(word, 0) + 1\nfor word, count in sorted(counts.items()):\n    print(word, count)`, quiz: ["items() 迭代得到什么？", ["key-value pair", "只有 key", "只有 value"], 0, "items() 返回可解包的键值对视图。"], homework: "完成 Inventory Manager 或 Word Frequency；必须使用函数、dictionary 更新、items() 遍历和至少三个测试案例。" },
    en: { title: "Dictionaries and a Word-Frequency Project", summary: "Model key-value data, access/update/delete/iterate dictionaries, and build inventory and word-frequency projects.", outcome: "Model real relationships with a dictionary and build a word counter with text preprocessing.", topics: [["Key-value", "Dictionaries are ordered in modern Python, mutable, and require unique keys; values may repeat."], ["Access and update", "Use [], get, keys/values/items; assignment adds or updates; pop/popitem removes."], ["Iteration", "Direct iteration yields keys; values() yields values; items() yields unpackable pairs."], ["Word frequency", "Lowercase, remove punctuation, split, then accumulate with get(word, 0)+1."]], demo: `students = {"Zoe": 99, "Yara": 88, "Diana": 92}\nstudents["Alice"] = 85\nfor name, score in students.items():\n    print(f"{name}: {score}")`, lab: `text = "The quick brown fox jumps over the lazy dog. The dog barked!"\nclean = text.lower()\nfor mark in ".,!?:;":\n    clean = clean.replace(mark, "")\ncounts = {}\nfor word in clean.split():\n    counts[word] = counts.get(word, 0) + 1\nfor word, count in sorted(counts.items()):\n    print(word, count)`, quiz: ["What does items() iterate over?", ["key-value pairs", "keys only", "values only"], 0, "items() provides an unpackable view of key-value pairs."], homework: "Complete an Inventory Manager or Word Frequency project using functions, dictionary updates, items() iteration, and three test cases." }
  }
];

module.exports = { lessons };
