"use strict";

// Course data for the Kaggle-centered, high-school-friendly 15-class pathway.
// Shared bilingual records keep the Chinese and English routes structurally aligned.

const pair = (zh, en) => ({ zh, en });
const quiz = (qZh, qEn, options, correct, explainZh, explainEn) => ({
  q: pair(qZh, qEn),
  options: options.map(([zh, en]) => pair(zh, en)),
  correct,
  explain: pair(explainZh, explainEn),
});

const commonMistakes = [
  [pair("只复制代码", "Copying code without understanding"), pair("至少修改一个值，并解释输出为什么改变。", "Change at least one value and explain why the output changes.")],
  [pair("一次改太多", "Changing too much at once"), pair("一次只改变一个变量，运行后再继续。", "Change one factor, rerun, and then continue.")],
  [pair("没有保存证据", "Not saving evidence"), pair("在Markdown中记录观察、结果和下一步。", "Record the observation, result, and next step in Markdown.")],
];

const kagglePath = "/kaggle/input/teacher-approved-dataset/data.csv";

const slideIds = [
  "title", "outputs", "lesson-agenda", "one-twenty-minute-pacing", "prerequisite-recap",
  "course-position", "dataset-context", "warmup", "vocabulary", "mental-model", "concept-1",
  "concept-2", "syntax-pattern", "teacher-demo", "code-trace", "prediction-check",
  "guided-practice-1", "guided-practice-2", "guided-lab", "mistake-clinic", "debug-routine",
  "checkpoint", "project-plan", "project-brief", "project-lab", "independent-work",
  "challenge-ladder", "concept-check", "evidence-handoff", "notebook-hygiene",
  "research-integrity", "rubric", "homework", "buffer-catchup", "exit-ticket",
];

const stageReviewTypes = {
  "prerequisite-recap": "current-materials",
  "dataset-context": "review-criteria",
  warmup: "student-status",
  vocabulary: "deliverable-language",
  "mental-model": "stage-goal",
  "concept-1": "student-code-explanation",
  "concept-2": "teacher-questions",
  "syntax-pattern": "evidence-audit",
  "teacher-demo": "review-conference",
  "code-trace": "revision-record",
  "guided-practice-1": "teacher-feedback",
  "guided-practice-2": "revision-plan",
  "guided-lab": "revision-time",
  "mistake-clinic": "project-risks",
  "debug-routine": "explain-code-routine",
  checkpoint: "stage-rubric-preview",
  "project-plan": "revision-log",
  "project-brief": "stage-submission",
  "project-lab": "submission-check",
  "challenge-ladder": "next-stage-gate",
  rubric: "stage-rubric",
};

const slideSchema = {
  knowledge: slideIds.map((id) => ({
    id,
    type: id.startsWith("concept-") ? "concept" : id,
    content: pair(`知识课页面：${id}`, `Knowledge-lesson slide: ${id}`),
  })),
  stage: slideIds.map((id) => ({
    id,
    type: stageReviewTypes[id] || id,
    content: pair(`Stage检查页面：${stageReviewTypes[id] || id}`, `Stage-review slide: ${stageReviewTypes[id] || id}`),
  })),
};

const stageReviews = {
  "04": {
    number: 1,
    goal: pair("确认研究问题、数据来源、许可、目标字段与Notebook v1均可继续推进。", "Approve the question, source, license, target field, and Notebook v1 for continued work."),
    materials: pair(["项目卡", "候选数据页面与核查记录", "数据字典", "可运行Notebook v1"], ["Project card", "Candidate-dataset page and verification record", "Data dictionary", "Runnable Notebook v1"]),
    criteria: pair(["问题可由现有字段检验", "数据状态不是 rejected", "目标为连续数值", "学生能解释启动代码"], ["Question is testable with available fields", "Dataset status is not rejected", "Target is continuous and numeric", "Student can explain the starter code"]),
    questions: pair(["哪个字段直接回答研究问题？", "哪些信息仍待人工核查？", "这段代码的输入、处理和输出是什么？"], ["Which field directly answers the question?", "Which facts still require manual review?", "What are this code block's input, process, and output?"]),
    risks: pair(["数据元信息不完整", "问题超出字段范围", "把合成数据当成真实因果证据"], ["Incomplete dataset metadata", "Question exceeds available fields", "Treating synthetic data as real causal evidence"]),
    nextGate: pair("完成读取、清洗、三张图和问题修订后进入Stage 2。", "Proceed to Stage 2 after loading, cleaning, three figures, and question revision."),
  },
  "08": {
    number: 2,
    goal: pair("确认原始数据、清洗记录、EDA图表和修订后的问题保持一致。", "Confirm alignment among raw data, cleaning records, EDA figures, and the revised question."),
    materials: pair(["原始数据", "clean.csv", "cleaning_log.csv", "三张核心图与观察"], ["Raw data", "clean.csv", "cleaning_log.csv", "Three core figures and observations"]),
    criteria: pair(["原始版本保留", "每个清洗决定有理由", "图表字段可追溯", "研究问题已按证据修订"], ["Raw version is preserved", "Every cleaning decision has a reason", "Figure fields are traceable", "Question is revised from evidence"]),
    questions: pair(["哪一步清洗改变了数据？", "最强的一张图回答了什么？", "你明确不能得出什么结论？"], ["Which cleaning step changed the data?", "What does the strongest figure answer?", "Which conclusion can you explicitly not make?"]),
    risks: pair(["用测试目标参与清洗", "图表与研究问题无关", "遗漏修改记录"], ["Using test targets during cleaning", "Figures unrelated to the question", "Missing revision records"]),
    nextGate: pair("确定少量数值特征、固定80/20拆分并运行Baseline后进入Stage 3。", "Proceed to Stage 3 after choosing a few numeric features, fixing the 80/20 split, and running the baseline."),
  },
  "12": {
    number: 3,
    goal: pair("确认DummyRegressor与LinearRegression在同一拆分、同一MAE指标下公平比较。", "Confirm a fair DummyRegressor and LinearRegression comparison on the same split and MAE metric."),
    materials: pair(["固定80/20拆分代码", "Baseline预测", "线性回归预测", "MAE表与最大错误记录"], ["Fixed 80/20 split code", "Baseline predictions", "Linear-regression predictions", "MAE table and largest-error records"]),
    criteria: pair(["random_state=42", "DummyRegressor(strategy='mean')", "较低MAE更好", "结论不作因果解释"], ["random_state=42", "DummyRegressor(strategy='mean')", "Lower MAE is better", "Claims avoid causal interpretation"]),
    questions: pair(["两个模型是否使用相同测试集？", "较低的MAE说明什么、不说明什么？", "最大误差提示了哪个限制？"], ["Did both models use the same test set?", "What does lower MAE show—and not show?", "Which limitation is suggested by the largest error?"]),
    risks: pair(["测试泄漏", "使用model.score()替代MAE", "把系数解释为因果"], ["Test leakage", "Using model.score() instead of MAE", "Interpreting coefficients causally"]),
    nextGate: pair("将可追溯证据写入Method、Results与Limitations后进入Stage 4。", "Proceed to Stage 4 after translating traceable evidence into Method, Results, and Limitations."),
  },
  "15": {
    number: 4,
    goal: pair("确认Notebook、Draft Paper、展示和后续修改清单形成可信交接包。", "Confirm that the notebook, Draft Paper, presentation, and revision list form a credible handoff package."),
    materials: pair(["可从上到下运行的Notebook", "Draft Paper v2", "5–8页展示", "教师反馈与修改清单"], ["Top-to-bottom runnable notebook", "Draft Paper v2", "5–8 slide presentation", "Instructor feedback and revision list"]),
    criteria: pair(["数字和图表可追溯", "学生能解释关键代码", "限制写清楚", "未承诺发表"], ["Numbers and figures are traceable", "Student explains key code", "Limitations are explicit", "Publication is not promised"]),
    questions: pair(["哪条结论最有证据？", "哪一段仍最需要修改？", "后续AI论文课先解决什么？"], ["Which claim has the strongest evidence?", "Which section needs the most revision?", "What should the follow-on AI paper course address first?"]),
    risks: pair(["论文数字与Notebook不一致", "学生无法解释AI生成代码", "把课程初稿包装成可发表论文"], ["Paper numbers differ from the notebook", "Student cannot explain AI-generated code", "Presenting a course draft as publication-ready"]),
    nextGate: pair("带着优先级明确的修改清单进入AI论文撰写课程。", "Enter the AI paper-writing course with a prioritized revision list."),
  },
};

const browserPackagesByLesson = {
  "01": [], "02": [], "03": [], "04": [],
  "05": ["pandas"], "06": ["pandas"], "07": ["pandas", "matplotlib"], "08": [],
  "09": ["scikit-learn"], "10": ["scikit-learn"], "11": ["pandas"], "12": [],
  "13": [], "14": [], "15": [],
};

const lessons = {
  "01": {
    title: pair("Kaggle、Notebook与Python入门", "Kaggle, Notebooks, and Python Foundations"),
    subtitle: pair("运行第一段代码，认识贯穿15节课的研究项目", "Run the first code and preview the research project that spans all 15 classes"),
    output: pair("创建一份可运行、可保存并包含科研实验日志的Kaggle Notebook。", "Create a runnable, saved Kaggle Notebook containing a research experiment log."),
    skills: [pair("打开并运行Notebook", "Open and run a notebook"), pair("变量、类型与清楚输出", "Variables, types, and clear output")],
    concepts: [[pair("Notebook", "Notebook"), pair("把代码、输出和研究说明放在同一份可复现文档中。", "A reproducible document that keeps code, output, and research notes together.")], [pair("变量与数据类型", "Variables and data types"), pair("用清楚的名字保存研究信息，并用int、float、str、bool区分信息类型。", "Use clear names to store research information and int, float, str, and bool to distinguish its type.")]],
    vocab: [[pair("Cell", "Cell"), pair("Notebook中可以单独运行的代码或文字区域。", "A runnable code or text block in a notebook.")], [pair("type", "type"), pair("检查一个值属于哪种数据类型。", "Check which data type a value belongs to.")]],
    syntax: `# A readable research record\nexperiment = "Seed Growth"   # str\nsample_count = 24            # int\ntemperature_c = 22.5         # float\nis_valid = True              # bool\n\nprint(type(sample_count))\nprint(f"{experiment}: n={sample_count}, {temperature_c} C")`,
    demo: `# Research experiment log\nexperiment = "Plant Light Test"\nresearcher = "Alex"\nsample_count = 12\ntemperature_c = 23.5\nis_valid = True\n\nprint("---- Research Log ----")\nprint(f"Experiment: {experiment}")\nprint(f"Researcher: {researcher}")\nprint(f"Samples: {sample_count}")\nprint(f"Temperature: {temperature_c} C")\nprint(f"Valid: {is_valid}")`,
    lab: { title: pair("第一份科研实验日志", "First Research Experiment Log"), intro: pair("先预测输出，再修改实验名称、样本量和温度；运行后用type()检查四种基础类型。", "Predict the output, then change the experiment name, sample count, and temperature; run it and use type() to check the four basic types."), code: `experiment = "Water Quality Test"\nsample_count = 20\ntemperature_c = 21.5\nis_complete = False\n\nprint(f"Experiment: {experiment}")\nprint(f"Samples: {sample_count}")\nprint(f"Temperature: {temperature_c} C")\nprint(f"Complete: {is_complete}")\nprint(type(experiment), type(sample_count), type(temperature_c), type(is_complete))` },
    project: { title: pair("我的科研实验日志", "My Research Experiment Log"), input: pair("实验名称、研究者、样本量、温度和有效状态。", "Experiment name, researcher, sample count, temperature, and validity status."), process: pair("用可读变量名和合适类型保存信息，再用注释和f-string组织输出。", "Store information with readable names and suitable types, then organize output with comments and f-strings."), output: pair("一份能从上到下运行并可分享的Notebook v0。", "A shareable Notebook v0 that runs from top to bottom."), code: `# My first research log\nexperiment = "My Experiment"\nresearcher = "My Name"\nsample_count = 10\ntemperature_c = 22.0\nis_valid = True\n\nprint("---- My Research Log ----")\nprint(f"Experiment: {experiment}")\nprint(f"Researcher: {researcher}")\nprint(f"Samples: {sample_count}")\nprint(f"Temperature: {temperature_c} C")\nprint(f"Valid: {is_valid}")` },
    quizzes: [quiz("Notebook最重要的作用是什么？", "What is the most important role of a notebook?", [["同时保存代码、输出和说明", "Keep code, output, and explanation together"], ["只展示漂亮图片", "Only display attractive images"], ["代替所有研究判断", "Replace all research judgment"]], 0, "Notebook应让分析过程可阅读、可运行、可复查。", "A notebook should make the analysis readable, runnable, and reviewable."), quiz("变量名应该优先表达什么？", "What should a variable name communicate?", [["保存的信息含义", "The meaning of the stored information"], ["代码作者年龄", "The author's age"], ["越短越好", "It should always be as short as possible"]], 0, "可读变量名能降低调试和解释难度。", "Readable names make debugging and explanation easier.")],
    stage: pair("共同基础 1/3", "Shared Foundation 1/3"), kaggleAction: pair("进入课程示例Notebook并保存副本。", "Open the course notebook and save a copy."), paperSection: pair("建立项目记录，不开始写论文。", "Create the project record; paper writing begins later."),
    mistakes: [[pair("文字忘记加引号", "Missing quotation marks around text"), pair("字符串必须放在成对引号中，否则Python会把它当成变量名。", "Text must be inside matching quotation marks or Python treats it as a variable name.")], [pair("变量名不清楚或前后拼写不一致", "Unclear or inconsistent variable names"), pair("使用sample_count这样的snake_case名字，并保持每次拼写一致。", "Use snake_case names such as sample_count and spell them consistently.")], [pair("修改后没有重新运行", "Not rerunning after a change"), pair("修改后从上到下重新运行，确认输出来自最新代码。", "After editing, rerun from top to bottom so the output matches the latest code.")]],
    homework: [pair("保存今天完成的Notebook副本", "Save a copy of today's completed notebook"), pair("把一个变量改成自己的真实兴趣或实验主题", "Change one variable to a real interest or experiment topic"), pair("从上到下运行并确认没有错误", "Run from top to bottom and confirm there are no errors"), pair("确认分享链接可以访问", "Confirm that the sharing link is accessible")],
    line: pair("先让代码运行，再让别人看懂它为什么这样运行。", "First make the code run; then make its purpose understandable."),
  },
  "02": {
    title: pair("条件、循环与数据质量", "Conditions, Loops, and Data Quality"),
    subtitle: pair("用简单规则检查Kaggle表格中的数值", "Use simple rules to check values in a Kaggle table"),
    output: pair("完成一个能标记正常值和待检查值的数据质量小程序。", "Build a small quality checker that labels normal and review-needed values."),
    skills: [pair("if判断", "if decisions"), pair("for循环", "for loops")],
    concepts: [[pair("条件", "Condition"), pair("结果为True或False的检查问题。", "A check whose result is True or False.")], [pair("循环", "Loop"), pair("把同一检查应用到多条记录。", "Apply the same check to many records.")]],
    vocab: [[pair("Threshold", "Threshold"), pair("规则使用的界线。", "The boundary used by a rule.")], [pair("Boundary case", "Boundary case"), pair("刚好位于界线附近的情况。", "A case exactly at or near a boundary.")]],
    syntax: `value = 105\nif 0 <= value <= 100:\n    label = "valid"\nelse:\n    label = "review"\nprint(label)`,
    demo: `scores = [88, 105, -2, 76]\nfor score in scores:\n    label = "valid" if 0 <= score <= 100 else "review"\n    print(score, label)`,
    lab: { title: pair("Dataset Value Checker", "Dataset Value Checker"), intro: pair("修改数值并专门测试0和100两个边界。", "Change the values and deliberately test the boundaries 0 and 100."), code: `values = [0, 72, 100, 108, -4]\nfor value in values:\n    if 0 <= value <= 100:\n        print(value, "valid")\n    else:\n        print(value, "review")` },
    project: { title: pair("项目字段检查规则", "Project Field Check Rules"), input: pair("项目中的一个数值字段。", "One numeric field from the project."), process: pair("确定合理范围并测试普通值和边界值。", "Define a reasonable range and test typical and boundary values."), output: pair("两条质量检查规则。", "Two data-quality rules."), code: `rules = {"study_hours": (0, 24), "score": (0, 100)}\nfor column, limits in rules.items():\n    print(column, limits)` },
    quizzes: [quiz("为什么必须测试边界值？", "Why must boundary values be tested?", [["边界最容易暴露规则错误", "Boundaries often reveal rule errors"], ["边界一定是缺失值", "Boundaries are always missing"], ["可以让数据更多", "They increase the dataset size"]], 0, "规则必须明确说明等于阈值时属于哪一类。", "A rule must define what happens exactly at the threshold."), quiz("for循环最适合做什么？", "What is a for loop best suited for?", [["对多条记录重复同一检查", "Repeat the same check across records"], ["自动选择研究题目", "Automatically choose a research topic"], ["证明因果关系", "Prove causation"]], 0, "循环减少重复代码。", "Loops reduce repeated code.")],
    stage: pair("共同基础 2/3", "Shared Foundation 2/3"), kaggleAction: pair("从候选数据集中观察可能需要检查的字段。", "Inspect fields in candidate datasets that may need quality checks."), paperSection: pair("记录数据可能存在的质量风险。", "Record possible data-quality risks."), line: pair("好规则不仅处理普通情况，也能解释边界。", "A good rule handles ordinary cases and explains boundaries."),
  },
  "03": {
    title: pair("函数、list与dict", "Functions, Lists, and Dictionaries"),
    subtitle: pair("只学习最终项目真正会使用的数据结构", "Learn only the structures the final project will actually use"),
    output: pair("完成一个可以重复使用的数据摘要函数。", "Complete a reusable data-summary function."),
    skills: [pair("定义函数", "Define functions"), pair("组织研究记录", "Organize research records")],
    concepts: [[pair("函数", "Function"), pair("给一段可重复使用的逻辑起名字。", "A named block of reusable logic.")], [pair("Dictionary", "Dictionary"), pair("用字段名保存一条结构清楚的研究记录。", "A structured record stored by named fields.")]],
    vocab: [[pair("Parameter", "Parameter"), pair("函数运行时需要的输入。", "An input required by a function.")], [pair("Return", "Return"), pair("函数交回给后续代码的结果。", "The result a function sends back.")]],
    syntax: `def summarize(values):\n    return min(values), sum(values) / len(values), max(values)\n\nprint(summarize([12, 18, 15, 21]))`,
    demo: `def project_record(topic, target):\n    return {"topic": topic, "target": target}\n\nrecord = project_record("Energy", "consumption")\nprint(record["target"])`,
    lab: { title: pair("Reusable Summary", "Reusable Summary"), intro: pair("把平均值和范围计算放进函数，再换一组数据测试。", "Put the average and range calculation in a function, then test new data."), code: `def describe(values):\n    average = sum(values) / len(values)\n    return {"count": len(values), "mean": average}\n\nprint(describe([3, 5, 7, 9]))` },
    project: { title: pair("项目立项数据结构", "Project Proposal Record"), input: pair("题目、Kaggle链接、目标变量和研究问题。", "Topic, Kaggle link, target variable, and research question."), process: pair("用dict保存，用函数检查必填字段。", "Store them in a dictionary and validate required fields with a function."), output: pair("Stage 1项目卡模板。", "Stage 1 project-card template."), code: `proposal = {"topic":"", "kaggle_url":"", "target":"", "question":""}\ndef missing_fields(record):\n    return [key for key, value in record.items() if not value]\nprint(missing_fields(proposal))` },
    quizzes: [quiz("return与print的主要区别是什么？", "What is the main difference between return and print?", [["return交回结果，print显示结果", "return sends back a value; print displays it"], ["完全相同", "They are identical"], ["return只能处理文字", "return only handles text"]], 0, "返回值可以继续被其他代码使用。", "A returned value can be reused by other code."), quiz("为什么项目记录适合使用dict？", "Why is a dictionary suitable for a project record?", [["字段有清楚名称", "Its fields have clear names"], ["它自动训练模型", "It trains a model automatically"], ["它只能保存数字", "It can store only numbers"]], 0, "topic、target等key让记录容易阅读。", "Keys such as topic and target make the record easy to read.")],
    stage: pair("共同基础 3/3", "Shared Foundation 3/3"), kaggleAction: pair("阅读教师候选登记表，并区分已核验与待人工复核。", "Read the instructor candidate registry and distinguish verified from pending items."), paperSection: pair("为Stage 1的数据字典做准备。", "Prepare for the Stage 1 data dictionary."), line: pair("函数让步骤可重复，dict让研究记录可阅读。", "Functions make steps reusable; dictionaries make research records readable."),
  },
  "04": {
    title: pair("Stage 1：Kaggle选题与项目启动", "Stage 1: Kaggle Topic and Project Launch"),
    subtitle: pair("融合研究问题、数据集审核与原始数据初检", "Combine the research question, dataset review, and first data audit"),
    output: pair("提交研究问题、Kaggle数据链接、许可证、数据字典和项目Notebook v1。", "Submit a research question, Kaggle link, license, data dictionary, and Project Notebook v1."),
    skills: [pair("审核数据集", "Review a dataset"), pair("收窄研究问题", "Narrow a research question")],
    concepts: [[pair("Dataset fit", "Dataset fit"), pair("数据字段是否真的能够回答研究问题。", "Whether the available fields can actually answer the question.")], [pair("Research question", "Research question"), pair("一个具体、可量化、能在课程内完成的问题。", "A specific, measurable question that fits the course timeline.")]],
    vocab: [[pair("License", "License"), pair("说明数据可以怎样使用与分享。", "States how the data may be used and shared.")], [pair("Data dictionary", "Data dictionary"), pair("记录变量名称、含义、单位和类型。", "Records each variable's name, meaning, unit, and type.")]],
    syntax: `import pandas as pd\ndf = pd.read_csv("${kagglePath}")\nprint(df.head())\nprint(df.shape)\nprint(df.columns.tolist())`,
    demo: `project = {\n    "question": "Can selected factors predict the target?",\n    "dataset_url": "https://www.kaggle.com/datasets/...",\n    "license": "CC0 or CC BY 4.0",\n    "target": "target_column"\n}\nprint(project)`,
    lab: { title: pair("Kaggle Dataset Audit", "Kaggle Dataset Audit"), intro: pair("在教师候选登记表中比较题目、核验状态、字段、许可证和难度。", "Compare topic, verification status, fields, license, and difficulty in the instructor candidate registry."), code: `checks = {"clear_source": True, "license_recorded": True, "tabular": True, "target_exists": True, "safe_scope": True}\nprint("Approved:", all(checks.values()))` },
    project: { title: pair("Stage 1 Gate", "Stage 1 Gate"), input: pair("教师登记并在开课前人工核验的3–5个Kaggle候选数据集。", "Three to five Kaggle candidates registered by the instructor and manually verified before class."), process: pair("选择主题、核对来源与许可、定义目标、运行原始数据初检。", "Choose a topic, verify source and license, define the target, and run a first audit."), output: pair("项目卡、数据字典和Notebook v1。", "Project card, data dictionary, and Notebook v1."), code: `stage1 = {"question":"", "dataset_url":"", "license":"", "target":"", "first_limit":""}\nfor key, value in stage1.items():\n    print(f"{key}: {value}")` },
    quizzes: [quiz("为什么不能让学生任意选择Kaggle数据？", "Why not allow any Kaggle dataset?", [["不同数据可能超出课程时间和技术范围", "Datasets may exceed the course's time and technical scope"], ["Kaggle没有表格数据", "Kaggle has no tabular data"], ["所有数据都完全相同", "All datasets are identical"]], 0, "教师候选登记与开课前人工核验在保留选择感的同时控制风险。", "An instructor registry plus pre-class manual verification preserves choice while controlling risk."), quiz("好的研究问题必须首先满足什么？", "What must a good research question satisfy first?", [["能由现有字段检验", "It can be tested with available fields"], ["必须使用复杂模型", "It must use a complex model"], ["结果必须显著", "Its result must be significant"]], 0, "研究问题必须与数据字段匹配。", "The research question must match the dataset fields.")],
    stage: pair("STAGE 1 / 4", "STAGE 1 / 4"), kaggleAction: pair("完成教师审核的数据集选择和Notebook启动。", "Complete instructor-approved dataset selection and launch the notebook."), paperSection: pair("确定题目、研究问题、数据来源和变量。", "Define the title, question, data source, and variables."), line: pair("先确认数据能回答问题，再开始写分析代码。", "Confirm that the data can answer the question before writing analysis code."),
  },
  "05": {
    title: pair("pandas读取、查看与筛选", "pandas: Read, Inspect, and Filter"),
    subtitle: pair("把共同技能直接应用到学生自己的Kaggle数据", "Apply a shared skill directly to each student's Kaggle data"),
    output: pair("完成项目数据概览，说明行数、列名、目标变量和一个筛选结果。", "Complete a project-data overview with rows, columns, target, and one filtered result."),
    skills: [pair("读取DataFrame", "Read a DataFrame"), pair("查看与筛选", "Inspect and filter")],
    concepts: [[pair("DataFrame", "DataFrame"), pair("带行列标签的数据表。", "A table with labeled rows and columns.")], [pair("Filter", "Filter"), pair("只保留符合研究条件的记录。", "Keep records that meet a research condition.")]],
    vocab: [[pair("Row", "Row"), pair("一条观察记录。", "One observation record.")], [pair("Column", "Column"), pair("一个研究变量。", "One research variable.")]],
    syntax: `import pandas as pd\ndf = pd.read_csv("${kagglePath}")\nprint(df.head())\nprint(df.shape)`,
    demo: `target = "performance_index"\nprint(df[target].describe())\nprint(df[df[target] >= df[target].median()].head())`,
    lab: { title: pair("Project Data Overview", "Project Data Overview"), intro: pair("先在无文件的小表格中练习，再把同一结构迁移到Kaggle Notebook。", "Practice first on a small file-free table, then transfer the same structure to the Kaggle notebook."), code: `import pandas as pd\ndf = pd.DataFrame({"hours": [2, 4, 6], "score": [60, 74, 88]})\nprint("Rows:", len(df))\nprint("Columns:", df.columns.tolist())\nprint(df.head(3))` },
    project: { title: pair("数据概览页", "Data Overview Page"), input: pair("Stage 1确定的Kaggle数据。", "The Kaggle data selected in Stage 1."), process: pair("读取、查看结构、选择目标并进行一次筛选。", "Read, inspect structure, select the target, and apply one filter."), output: pair("Notebook中的Data Overview章节。", "A Data Overview section in the notebook."), code: `overview = {"rows": len(df), "columns": len(df.columns), "target": target}\nprint(overview)` },
    quizzes: [quiz("读取数据后第一步应该做什么？", "What should happen immediately after reading data?", [["查看head、shape和columns", "Inspect head, shape, and columns"], ["直接训练模型", "Train a model immediately"], ["删除所有缺失值", "Delete all missing values"]], 0, "先理解数据结构，再决定处理方法。", "Understand the structure before deciding how to process it."), quiz("筛选会改变原始文件吗？", "Does filtering automatically change the original file?", [["不会，只产生满足条件的结果", "No; it produces a selected result"], ["一定会删除原文件", "Yes; it always deletes the source file"], ["会自动发表论文", "It automatically publishes a paper"]], 0, "除非显式保存，否则筛选不会覆盖原始CSV。", "Filtering does not overwrite the source CSV unless explicitly saved.")],
    stage: pair("Stage 2准备 1/3", "Stage 2 Preparation 1/3"), kaggleAction: pair("读取自己的数据并建立Data Overview。", "Read the selected dataset and build a Data Overview."), paperSection: pair("积累Dataset and Variables材料。", "Build material for Dataset and Variables."), line: pair("先看懂表格，再开始计算。", "Understand the table before calculating."),
  },
  "06": {
    title: pair("数据清洗与决策日志", "Data Cleaning and Decision Logs"),
    subtitle: pair("清理问题，同时保留每个决定的理由", "Repair data problems while preserving the reason for every decision"),
    output: pair("生成clean.csv和至少三条清洗决策记录。", "Produce clean.csv and at least three cleaning-decision records."),
    skills: [pair("发现数据问题", "Detect data problems"), pair("记录清洗决定", "Document cleaning decisions")],
    concepts: [[pair("Missing value", "Missing value"), pair("某项信息没有被记录。", "A value that was not recorded.")], [pair("Decision log", "Decision log"), pair("记录做了什么、为什么以及影响多少记录。", "Records what changed, why, and how many records were affected.")]],
    vocab: [[pair("NaN", "NaN"), pair("pandas常见的缺失值标记。", "A common pandas marker for missing data.")], [pair("Duplicate", "Duplicate"), pair("重复出现的记录。", "A repeated record.")]],
    syntax: `print(df.isna().sum())\nprint("duplicates:", df.duplicated().sum())\ndf = df.drop_duplicates()`,
    demo: `decisions = []\nbefore = len(df)\ndf = df.drop_duplicates()\ndecisions.append({"step":"drop_duplicates", "rows_changed": before-len(df), "reason":"same record repeated"})\nprint(decisions)`,
    lab: { title: pair("Cleaning with Evidence", "Cleaning with Evidence"), intro: pair("在无文件小表格中记录清洗决定；项目数据的清洗只在Kaggle Notebook完成。", "Log a cleaning decision on a small file-free table; clean the project dataset only in Kaggle."), code: `import pandas as pd\ndf = pd.DataFrame({"hours": [2, None, 6], "score": [60, 74, 88]})\nmissing_before = int(df["hours"].isna().sum())\ndf["hours"] = df["hours"].fillna(df["hours"].median())\nprint("filled:", missing_before)\nprint(df)` },
    project: { title: pair("项目清洗记录", "Project Cleaning Record"), input: pair("项目原始DataFrame。", "The raw project DataFrame."), process: pair("检查、选择方法、记录理由、保存新文件。", "Inspect, choose a method, record the reason, and save a new file."), output: pair("clean.csv与cleaning_log.csv。", "clean.csv and cleaning_log.csv."), code: `df.to_csv("clean.csv", index=False)\npd.DataFrame(decisions).to_csv("cleaning_log.csv", index=False)\nprint("saved", len(df), "rows")` },
    quizzes: [quiz("发现异常值后应该立即删除吗？", "Should an unusual value be deleted immediately?", [["不一定，先检查来源和研究含义", "Not necessarily; first check its source and meaning"], ["一定删除", "Always delete it"], ["永远保留", "Always keep it"]], 0, "异常值可能是错误，也可能是真实的重要现象。", "An unusual value may be an error or a meaningful real case."), quiz("为什么保存清洗日志？", "Why save a cleaning log?", [["让处理过程可复查和可复现", "Make processing reviewable and reproducible"], ["让文件更多", "Create more files"], ["代替原始数据", "Replace the raw data"]], 0, "研究项目必须能说明数据如何改变。", "A research project must explain how its data changed.")],
    stage: pair("Stage 2准备 2/3", "Stage 2 Preparation 2/3"), kaggleAction: pair("清理自己的数据，但始终保留原始版本。", "Clean the project data while preserving the raw version."), paperSection: pair("积累Data Processing材料。", "Build material for Data Processing."), line: pair("清洗不是让数据变漂亮，而是让决定有证据。", "Cleaning is not making data look pretty; every decision needs evidence."),
  },
  "07": {
    title: pair("可视化、简单统计与数据观察", "Visualization, Simple Statistics, and Observations"),
    subtitle: pair("用三种基础图表寻找与研究问题有关的现象", "Use three basic charts to find patterns related to the research question"),
    output: pair("完成三张核心图和三条不夸大的数据观察。", "Complete three core charts and three careful data observations."),
    skills: [pair("选择基础图表", "Choose basic charts"), pair("写证据观察", "Write evidence-based observations")],
    concepts: [[pair("Distribution", "Distribution"), pair("一个数值的集中、范围和形状。", "The center, range, and shape of a numeric variable.")], [pair("Relationship", "Relationship"), pair("两个变量如何一起变化。", "How two variables change together.")]],
    vocab: [[pair("Histogram", "Histogram"), pair("查看一个数值变量的分布。", "Shows the distribution of one numeric variable.")], [pair("Scatterplot", "Scatterplot"), pair("查看两个数值变量之间的关系。", "Shows the relationship between two numeric variables.")]],
    syntax: `import matplotlib.pyplot as plt\ndf[target].hist()\nplt.title("Target distribution")\nplt.xlabel(target)\nplt.show()`,
    demo: `df.plot.scatter(x="feature_column", y=target)\nplt.title("Feature and target")\nplt.show()`,
    lab: { title: pair("Small-Table EDA", "Small-Table EDA"), intro: pair("在无文件小表格中完成一张关系图并说出字段来源。", "Create one relationship chart on a small file-free table and name the source fields."), code: `import pandas as pd\nimport matplotlib.pyplot as plt\ndf = pd.DataFrame({"hours": [1, 2, 3, 4], "score": [55, 63, 72, 84]})\ndf.plot.scatter(x="hours", y="score")\nplt.title("Hours and score")\nplt.show()` },
    project: { title: pair("项目图表证据包", "Project Figure Evidence Pack"), input: pair("清洗后的项目数据。", "Clean project data."), process: pair("一张图回答一个问题，并写观察与限制。", "Use one figure per question and write an observation and limitation."), output: pair("3张图、3条观察和1条不能得出的结论。", "Three figures, three observations, and one claim the data cannot support."), code: `observations = [\n    "Figure 1 shows...",\n    "Figure 2 suggests...",\n    "This does not prove causation."\n]\nfor item in observations:\n    print(item)` },
    quizzes: [quiz("查看两个数值变量关系应优先使用什么图？", "Which chart is preferred for two numeric variables?", [["散点图", "Scatterplot"], ["饼图", "Pie chart"], ["单个数字", "One number"]], 0, "散点图保留每条观察的两个数值。", "A scatterplot preserves both numeric values for each observation."), quiz("相关现象能直接证明因果吗？", "Does an observed relationship prove causation?", [["不能", "No"], ["总能", "Always"], ["只有正相关能", "Only a positive relationship can"]], 0, "观察性数据通常只能支持关系描述。", "Observational data usually supports association, not causation.")],
    stage: pair("Stage 2准备 3/3", "Stage 2 Preparation 3/3"), kaggleAction: pair("把三张核心图保存到项目Notebook。", "Save three core figures in the project notebook."), paperSection: pair("积累Figures与Results材料。", "Build material for Figures and Results."), line: pair("图表不是装饰；每张图都应回答一个问题。", "A figure is not decoration; each figure should answer a question."),
  },
  "08": {
    title: pair("Stage 2：数据处理与EDA检查点", "Stage 2: Data Processing and EDA Checkpoint"),
    subtitle: pair("把第5–7节技能完整应用到学生自己的选题", "Apply Classes 5–7 completely to each student's topic"),
    output: pair("提交clean.csv、清洗日志、三张图、三条观察和修订后的研究问题。", "Submit clean.csv, a cleaning log, three figures, three observations, and a revised question."),
    skills: [pair("整合数据流程", "Integrate the data workflow"), pair("用EDA修订问题", "Revise the question with EDA")],
    concepts: [[pair("EDA checkpoint", "EDA checkpoint"), pair("建模前检查数据是否仍然支持研究问题。", "A pre-modeling check that the data still supports the question.")], [pair("Reproducibility", "Reproducibility"), pair("别人能够按照记录重复数据处理和图表。", "Others can repeat the processing and figures from the record.")]],
    vocab: [[pair("Raw data", "Raw data"), pair("未经学生处理的原始版本。", "The original version before student processing.")], [pair("Clean data", "Clean data"), pair("根据记录明确的规则处理后的版本。", "A version processed using clearly documented rules.")]],
    syntax: `required = ["clean.csv", "cleaning_log.csv", "figure_1.png", "figure_2.png", "figure_3.png"]\nfor item in required:\n    print("CHECK:", item)`,
    demo: `stage2 = {"question_revised": True, "clean_data_saved": True, "decisions_recorded": True, "figures": 3, "observations": 3}\nprint("Stage 2 ready:", all([stage2["question_revised"], stage2["clean_data_saved"], stage2["decisions_recorded"], stage2["figures"] >= 3]))`,
    lab: { title: pair("EDA Review Conference", "EDA Review Conference"), intro: pair("学生用三分钟说明数据变化、图表证据和研究问题调整。", "Use three minutes to explain data changes, figure evidence, and the revised question."), code: `review = {"strongest_figure":"", "main_observation":"", "question_change":"", "remaining_risk":""}\nfor key, value in review.items():\n    print(f"{key}: {value}")` },
    project: { title: pair("Stage 2 Gate", "Stage 2 Gate"), input: pair("原始数据、清洗Notebook和EDA图表。", "Raw data, cleaning notebook, and EDA figures."), process: pair("逐项检查文件、代码、说明和研究问题的一致性。", "Check files, code, explanations, and question alignment."), output: pair("可进入建模阶段的项目数据包。", "A project data package ready for modeling."), code: `assert len(df) > 0\nassert target in df.columns\nassert df[target].notna().all()\nprint("Modeling dataset ready")` },
    quizzes: [quiz("EDA后可以修改研究问题吗？", "May the research question change after EDA?", [["可以，但必须记录理由", "Yes, with a documented reason"], ["永远不能", "Never"], ["只有删除数据后可以", "Only after deleting data"]], 0, "真实数据经常要求我们收窄问题。", "Real data often requires narrowing the question."), quiz("Stage 2最重要的通过条件是什么？", "What is the most important Stage 2 gate?", [["数据、图表和问题互相一致", "Data, figures, and question align"], ["图表颜色最多", "The figures use many colors"], ["代码行数最多", "The notebook has the most code"]], 0, "项目主线比代码数量重要。", "Project coherence matters more than code quantity.")],
    stage: pair("STAGE 2 / 4", "STAGE 2 / 4"), kaggleAction: pair("提交Kaggle Notebook的Data、Cleaning与EDA章节。", "Submit the Data, Cleaning, and EDA sections of the Kaggle notebook."), paperSection: pair("形成Dataset、Data Processing和初步Results素材。", "Form material for Dataset, Data Processing, and preliminary Results."), line: pair("项目数据不仅要干净，还必须与研究问题相连。", "Project data must be clean and connected to the research question."),
  },
  "09": {
    title: pair("特征、目标、训练集与Baseline", "Features, Target, Train/Test, and Baseline"),
    subtitle: pair("用最简单的模型建立诚实的比较起点", "Build an honest comparison point with the simplest model"),
    output: pair("确定项目特征与目标，完成训练测试拆分和DummyRegressor结果。", "Define project features and target, split the data, and produce a DummyRegressor result."),
    skills: [pair("拆分训练测试集", "Split train and test data"), pair("建立Baseline", "Build a baseline")],
    concepts: [[pair("Feature / target", "Feature / target"), pair("模型使用的输入和希望预测的数值。", "The model inputs and the numeric outcome to predict.")], [pair("Baseline", "Baseline"), pair("不学习复杂规律的简单比较起点。", "A simple comparison point that does not learn complex patterns.")]],
    vocab: [[pair("fit", "fit"), pair("让模型从训练数据学习。", "Learn from training data.")], [pair("predict", "predict"), pair("对新输入生成预测。", "Produce predictions for new inputs.")]],
    syntax: `from sklearn.model_selection import train_test_split\nX_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)`,
    demo: `from sklearn.dummy import DummyRegressor\nbaseline = DummyRegressor(strategy="mean")\nbaseline.fit(X_train, y_train)\nbaseline_pred = baseline.predict(X_test)`,
    lab: { title: pair("First Baseline", "First Baseline"), intro: pair("在无文件小样本中运行平均值Baseline并计算MAE。", "Run a mean baseline and calculate MAE on a small file-free sample."), code: `from sklearn.dummy import DummyRegressor\nfrom sklearn.metrics import mean_absolute_error\nX_train = [[1], [2], [3], [4]]\ny_train = [52, 61, 70, 79]\nX_test = [[5], [6]]\ny_test = [86, 92]\nbaseline = DummyRegressor(strategy="mean")\nbaseline.fit(X_train, y_train)\nbaseline_pred = baseline.predict(X_test)\nprint("Baseline MAE:", round(mean_absolute_error(y_test, baseline_pred), 2))` },
    project: { title: pair("项目建模数据表", "Project Modeling Table"), input: pair("Stage 2通过的clean.csv。", "The clean.csv approved at Stage 2."), process: pair("选择少量数值特征、确定目标、固定拆分、运行Baseline。", "Choose a small set of numeric features, define the target, fix the split, and run a baseline."), output: pair("特征表、目标说明和Baseline MAE。", "Feature table, target statement, and baseline MAE."), code: `features = ["feature_1", "feature_2"]\nX = df[features]\ny = df[target]\nprint("X:", X.shape, "y:", y.shape)` },
    quizzes: [quiz("为什么测试集不能参与训练？", "Why must the test set stay out of training?", [["要模拟模型面对未见数据的表现", "It represents unseen data"], ["测试集不能有数字", "Test data cannot contain numbers"], ["为了让代码更短", "To shorten the code"]], 0, "测试集必须保持独立。", "The test set must remain independent."), quiz("Baseline的作用是什么？", "What is the role of a baseline?", [["提供比较起点", "Provide a comparison point"], ["保证模型完美", "Guarantee a perfect model"], ["替代研究问题", "Replace the research question"]], 0, "没有Baseline就不知道模型是否真正改进。", "Without a baseline, improvement has no clear meaning.")],
    stage: pair("Stage 3准备 1/3", "Stage 3 Preparation 1/3"), kaggleAction: pair("在项目Notebook建立Modeling章节和固定拆分。", "Create the Modeling section and one fixed split."), paperSection: pair("积累Method中的数据拆分和Baseline描述。", "Build the split and baseline description for Method."), line: pair("先建立简单而诚实的起点，再谈改进。", "Build a simple, honest starting point before improvement."),
  },
  "10": {
    title: pair("一个简单模型：线性回归", "One Simple Model: Linear Regression"),
    subtitle: pair("模型是回答研究问题的工具，不是课程主角", "The model is a tool for the question, not the star of the course"),
    output: pair("训练LinearRegression并保存预测、系数和运行记录。", "Train LinearRegression and save predictions, coefficients, and run details."),
    skills: [pair("训练线性模型", "Train a linear model"), pair("解释模型输入输出", "Explain model input and output")],
    concepts: [[pair("Linear model", "Linear model"), pair("用输入的加权组合预测一个数值。", "Predicts a number from a weighted combination of inputs.")], [pair("Coefficient", "Coefficient"), pair("描述其他条件不变时某个输入与预测的关系方向。", "Describes the direction of an input's relationship with the prediction, holding other inputs fixed.")]],
    vocab: [[pair("Model", "Model"), pair("从数据中学习输入到输出关系的规则。", "A rule learned from data that maps inputs to outputs.")], [pair("Prediction", "Prediction"), pair("模型对一条新记录给出的结果。", "The model output for a new record.")]],
    syntax: `from sklearn.linear_model import LinearRegression\nmodel = LinearRegression()\nmodel.fit(X_train, y_train)\npred = model.predict(X_test)`,
    demo: `for name, value in zip(features, model.coef_):\n    print(name, round(value, 3))`,
    lab: { title: pair("Baseline vs Linear Model", "Baseline vs Linear Model"), intro: pair("在无文件小样本中训练线性回归；项目比较仍使用第9课固定拆分。", "Train linear regression on a small file-free sample; the project comparison still uses the fixed Class 9 split."), code: `from sklearn.linear_model import LinearRegression\nX_train = [[1], [2], [3], [4]]\ny_train = [52, 61, 70, 79]\nX_test = [[5], [6]]\ny_test = [86, 92]\nmodel = LinearRegression()\nmodel.fit(X_train, y_train)\nlinear_pred = model.predict(X_test)\nprint("predictions:", linear_pred.round(1).tolist())\nprint("actual:", y_test)` },
    project: { title: pair("项目核心模型", "Project Core Model"), input: pair("与Baseline相同的特征、目标和拆分。", "The same features, target, and split used by the baseline."), process: pair("训练一个LinearRegression并记录代码版本。", "Train one LinearRegression and record the code version."), output: pair("模型对象、预测结果和系数表。", "Model object, predictions, and coefficient table."), code: `coefficients = pd.DataFrame({"feature": features, "coefficient": model.coef_})\nprint(coefficients)` },
    quizzes: [quiz("第一期课程要求多少个核心模型？", "How many core models are required in the first course?", [["Baseline加一个线性模型", "A baseline plus one linear model"], ["至少十个", "At least ten"], ["越多越好", "As many as possible"]], 0, "目标是理解、公平比较和解释。", "The goal is understanding, fair comparison, and explanation."), quiz("系数可以直接证明因果吗？", "Does a coefficient prove causation?", [["不能", "No"], ["总能", "Always"], ["系数为正时能", "Only when positive"]], 0, "模型关系受到数据质量和研究设计限制。", "Model relationships are limited by data quality and research design.")],
    stage: pair("Stage 3准备 2/3", "Stage 3 Preparation 2/3"), kaggleAction: pair("在Kaggle Notebook中训练唯一必修模型。", "Train the single required model in the Kaggle notebook."), paperSection: pair("积累Method中的模型说明。", "Build the model description for Method."), line: pair("模型是回答问题的工具，不是研究故事的主角。", "The model is a tool for the question, not the main character."),
  },
  "11": {
    title: pair("MAE、错误分析与公平比较", "MAE, Error Analysis, and Fair Comparison"),
    subtitle: pair("只用一个核心指标判断模型是否优于Baseline", "Use one core metric to judge whether the model improves on the baseline"),
    output: pair("完成Baseline与LinearRegression的MAE比较表和一段错误分析。", "Complete a baseline-versus-linear MAE table and one error-analysis paragraph."),
    skills: [pair("计算MAE", "Calculate MAE"), pair("分析错误案例", "Analyze error cases")],
    concepts: [[pair("MAE", "MAE"), pair("预测值与真实值平均相差多少，单位与目标相同。", "The average absolute prediction error, in the target's original unit.")], [pair("Fair comparison", "Fair comparison"), pair("使用相同数据拆分和评价指标比较模型。", "Compare models with the same split and metric.")]],
    vocab: [[pair("Residual", "Residual"), pair("真实值减去预测值的差。", "The difference between the observed and predicted value.")], [pair("Error pattern", "Error pattern"), pair("模型在哪类记录上更容易预测不准。", "The kinds of records on which the model is less accurate.")]],
    syntax: `from sklearn.metrics import mean_absolute_error\nbaseline_mae = mean_absolute_error(y_test, baseline_pred)\nlinear_mae = mean_absolute_error(y_test, linear_pred)`,
    demo: `results = pd.DataFrame({"actual": y_test, "predicted": linear_pred})\nresults["absolute_error"] = (results["actual"] - results["predicted"]).abs()\nprint(results.sort_values("absolute_error", ascending=False).head())`,
    lab: { title: pair("Model Scorecard", "Model Scorecard"), intro: pair("用已给出的两个MAE制作两行比较表，并判断哪个更好。", "Build a two-row comparison from two supplied MAE values and identify the better result."), code: `import pandas as pd\nbaseline_mae = 14.5\nlinear_mae = 6.2\nscorecard = pd.DataFrame({"model":["Dummy baseline", "Linear regression"], "MAE":[baseline_mae, linear_mae]})\nprint(scorecard)\nprint("Better:", scorecard.loc[scorecard["MAE"].idxmin(), "model"])` },
    project: { title: pair("评价证据包", "Evaluation Evidence Pack"), input: pair("两个模型在同一测试集上的预测。", "Predictions from both models on the same test set."), process: pair("计算MAE、比较变化、检查最大误差并写限制。", "Calculate MAE, compare change, inspect largest errors, and state a limitation."), output: pair("模型评价表和错误分析段落。", "A model scorecard and error-analysis paragraph."), code: `improvement = baseline_mae - linear_mae\nprint("MAE improvement:", round(improvement, 2))\nprint("Lower MAE is better")` },
    quizzes: [quiz("MAE越低通常表示什么？", "What does a lower MAE usually indicate?", [["平均预测误差更小", "Smaller average prediction error"], ["数据一定没有偏差", "The data has no bias"], ["证明了因果关系", "Causation is proven"]], 0, "MAE只描述预测误差，不证明研究设计没有问题。", "MAE describes prediction error; it does not validate the entire research design."), quiz("公平比较两个模型需要什么？", "What is required for a fair model comparison?", [["相同测试集和相同指标", "The same test set and metric"], ["不同测试集", "Different test sets"], ["只报告最好一次", "Report only the best run"]], 0, "统一条件才能把差异归因于模型。", "Shared conditions isolate the model difference.")],
    stage: pair("Stage 3准备 3/3", "Stage 3 Preparation 3/3"), kaggleAction: pair("保存scorecard与最大错误记录。", "Save the scorecard and largest-error records."), paperSection: pair("积累Results与Limitations材料。", "Build material for Results and Limitations."), line: pair("一个分数不是结论；还要解释错误和限制。", "A score is not a conclusion; explain errors and limitations."),
  },
  "12": {
    title: pair("Stage 3：建模与结果检查点", "Stage 3: Modeling and Results Checkpoint"),
    subtitle: pair("完成Baseline、线性模型、MAE和可解释结果表", "Complete the baseline, linear model, MAE, and an interpretable results table"),
    output: pair("提交可重复运行的Modeling章节、模型评价表、关键结果图和选择理由。", "Submit a reproducible Modeling section, scorecard, key result figure, and model rationale."),
    skills: [pair("整合建模流程", "Integrate the modeling workflow"), pair("把结果写成证据", "Turn results into evidence")],
    concepts: [[pair("Controlled comparison", "Controlled comparison"), pair("一次只改变模型，其他评价条件保持一致。", "Change only the model while holding evaluation conditions constant.")], [pair("Evidence statement", "Evidence statement"), pair("同时包含条件、结果和限制的研究陈述。", "A research statement that includes condition, result, and limitation.")]],
    vocab: [[pair("Scorecard", "Scorecard"), pair("用统一指标比较模型的简表。", "A compact table that compares models with one metric.")], [pair("Reproducibility note", "Reproducibility note"), pair("说明如何重新运行数据处理和模型。", "Explains how to rerun processing and modeling.")]],
    syntax: `required_results = {"baseline_mae": baseline_mae, "linear_mae": linear_mae, "test_rows": len(y_test), "random_state": 42}\nprint(required_results)`,
    demo: `claim = f"On the held-out test set, linear regression changed MAE from {baseline_mae:.2f} to {linear_mae:.2f}. This result applies only to the selected dataset and split."\nprint(claim)`,
    lab: { title: pair("Model Review Conference", "Model Review Conference"), intro: pair("学生用三分钟说明输入、模型、指标、结果和一个限制。", "Use three minutes to explain inputs, model, metric, result, and one limitation."), code: `review = {"features": features, "target": target, "metric":"MAE", "result":"", "limitation":""}\nprint(review)` },
    project: { title: pair("Stage 3 Gate", "Stage 3 Gate"), input: pair("固定拆分、Baseline和LinearRegression结果。", "Fixed split, baseline, and linear-regression results."), process: pair("从头运行、检查表格、核对文字与数字、说明限制。", "Run from the top, verify the table, match prose to numbers, and state limitations."), output: pair("可进入论文写作的模型证据包。", "A modeling evidence pack ready for paper writing."), code: `assert baseline_pred.shape == linear_pred.shape\nassert len(linear_pred) == len(y_test)\nprint("Stage 3 evidence ready")` },
    quizzes: [quiz("Results段最应该报告什么？", "What belongs most directly in Results?", [["观察到的证据", "Observed evidence"], ["未经支持的猜测", "Unsupported guesses"], ["所有背景知识", "All background knowledge"]], 0, "Results报告发生了什么，Discussion解释可能意味着什么。", "Results reports what happened; Discussion interprets what it may mean."), quiz("Stage 3为什么不要求更多模型？", "Why does Stage 3 not require more models?", [["课程重点是理解和证据链", "The course prioritizes understanding and the evidence chain"], ["Python不能运行其他模型", "Python cannot run other models"], ["MAE只能用于一个模型", "MAE works for only one model"]], 0, "少量模型更适合高中生完成公平、可解释的比较。", "A small model set supports fair, explainable comparison for beginners.")],
    stage: pair("STAGE 3 / 4", "STAGE 3 / 4"), kaggleAction: pair("提交完整Modeling与Evaluation章节。", "Submit complete Modeling and Evaluation sections."), paperSection: pair("形成Method、Results和Limitations的模型材料。", "Form model material for Method, Results, and Limitations."), line: pair("结论必须比证据更谨慎，不能比证据更宽。", "A conclusion must be narrower than the evidence, not wider."),
  },
  "13": {
    title: pair("从代码到Method与Results", "From Code to Method and Results"),
    subtitle: pair("把Notebook步骤转写成高中生能够解释的论文段落", "Turn notebook steps into paper paragraphs a high-school student can explain"),
    output: pair("完成Method、Results、图表标题和一段Limitations初稿。", "Complete drafts of Method, Results, figure captions, and one Limitations paragraph."),
    skills: [pair("从代码写方法", "Write methods from code"), pair("用数字写结果", "Write results with numbers")],
    concepts: [[pair("Method", "Method"), pair("说明数据、处理、拆分、模型和评价步骤。", "Explains data, processing, split, model, and evaluation steps.")], [pair("Results", "Results"), pair("报告图表和指标显示的证据，不加入未经支持的解释。", "Reports evidence from figures and metrics without unsupported interpretation.")]],
    vocab: [[pair("Figure caption", "Figure caption"), pair("说明图表展示什么以及读者应关注什么。", "States what a figure shows and what the reader should notice.")], [pair("Limitation", "Limitation"), pair("明确结论适用范围和仍然未知的部分。", "Defines the valid scope of the conclusion and what remains unknown.")]],
    syntax: `method = {"data":"Kaggle dataset and license", "cleaning":"documented rules", "split":"80/20, random_state=42", "models":"DummyRegressor and LinearRegression", "metric":"MAE"}\nfor key, value in method.items():\n    print(key, value)`,
    demo: `result_sentence = f"Linear regression achieved an MAE of {linear_mae:.2f}, compared with {baseline_mae:.2f} for the mean baseline."\nlimit_sentence = "These findings describe this selected dataset and do not prove causation."\nprint(result_sentence)\nprint(limit_sentence)`,
    lab: { title: pair("Code-to-Paper Translation", "Code-to-Paper Translation"), intro: pair("选择五段关键代码，为每段写一句方法说明。", "Select five key code blocks and write one method sentence for each."), code: `paper_map = {"read_csv":"Data source", "drop_duplicates":"Data processing", "train_test_split":"Evaluation design", "LinearRegression":"Model", "mean_absolute_error":"Metric"}\nprint(paper_map)` },
    project: { title: pair("Draft Paper Sections v0", "Draft Paper Sections v0"), input: pair("Stage 1–3项目证据。", "Evidence from Stages 1–3."), process: pair("按代码顺序写Method，按图表顺序写Results。", "Write Method in code order and Results in figure order."), output: pair("Method与Results初稿。", "Method and Results draft."), code: `draft_status = {"method": "drafted", "results": "drafted", "figure_captions": 3, "limitations": 1}\nprint(draft_status)` },
    quizzes: [quiz("Method应该主要回答什么？", "What should Method mainly answer?", [["研究是怎样完成的", "How the study was carried out"], ["结果是否令人兴奋", "Whether the result is exciting"], ["作者喜欢什么颜色", "Which colors the author likes"]], 0, "Method要让别人能够理解并重复流程。", "Method should make the workflow understandable and repeatable."), quiz("Results中可以写模型证明了因果吗？", "May Results state that the model proves causation?", [["不能", "No"], ["只要MAE很低就能", "Yes, if MAE is low"], ["只要使用Kaggle就能", "Yes, if Kaggle was used"]], 0, "预测模型和观察性数据通常不能证明因果。", "A prediction model on observational data usually cannot prove causation.")],
    stage: pair("论文交接准备 1/2", "Paper Handoff Preparation 1/2"), kaggleAction: pair("固定最终Notebook中的代码、表格和图表编号。", "Freeze the notebook's final code, tables, and figure numbering."), paperSection: pair("完成Method、Results和初步Limitations。", "Complete Method, Results, and preliminary Limitations."), line: pair("论文不是重新发明故事，而是准确整理已有证据。", "A paper does not invent a new story; it organizes existing evidence accurately."),
  },
  "14": {
    title: pair("Draft Paper写作工作坊", "Draft Paper Writing Workshop"),
    subtitle: pair("完成摘要、引言、讨论、结论和5–8页展示", "Complete the abstract, introduction, discussion, conclusion, and a 5–8 slide deck"),
    output: pair("形成4–6页Draft Paper v1和5–8页项目展示初稿。", "Produce a 4–6 page Draft Paper v1 and a 5–8 slide presentation draft."),
    skills: [pair("组织研究故事", "Organize the research story"), pair("区分证据与解释", "Separate evidence from interpretation")],
    concepts: [[pair("IMRaD", "IMRaD"), pair("Introduction、Method、Results和Discussion构成论文主干。", "Introduction, Method, Results, and Discussion form the paper's core.")], [pair("Abstract", "Abstract"), pair("用简短文字概括问题、数据、方法、结果和限制。", "Briefly summarizes the question, data, method, result, and limitation.")]],
    vocab: [[pair("Claim", "Claim"), pair("作者根据证据提出的研究陈述。", "A research statement supported by evidence.")], [pair("Reference", "Reference"), pair("明确记录数据、资料和他人工作的来源。", "A clear record of data, sources, and prior work.")]],
    syntax: `paper_sections = ["Title", "Abstract", "Introduction", "Research Question", "Dataset and Variables", "Data Processing", "Method", "Results", "Discussion", "Limitations", "Conclusion", "References"]\nfor i, section in enumerate(paper_sections, 1):\n    print(i, section)`,
    demo: `abstract_plan = {"question":"1 sentence", "data":"1 sentence", "method":"1 sentence", "result":"1–2 sentences with MAE", "limitation":"1 sentence"}\nprint(abstract_plan)`,
    lab: { title: pair("Draft Paper Assembly", "Draft Paper Assembly"), intro: pair("把Stage 1–3成果放进统一模板，先完成内容再润色。", "Place Stage 1–3 evidence into one template; complete content before polishing."), code: `deliverables = {"paper_pages":"4–6", "figures":"3–5", "slides":"5–8", "notebook_runnable":True, "kaggle_links":True}\nprint(deliverables)` },
    project: { title: pair("Draft Paper v1", "Draft Paper v1"), input: pair("研究问题、数据来源、代码、图表、结果和限制。", "Question, data source, code, figures, results, and limitations."), process: pair("按模板组装、核对数字、补充引用并进行一次教师反馈。", "Assemble the template, verify numbers, add references, and complete one instructor review."), output: pair("4–6页论文初稿和展示初稿。", "A 4–6 page paper draft and presentation draft."), code: `checks = ["question matches data", "methods match notebook", "numbers match scorecard", "figures have captions", "limitations are explicit", "Kaggle URL and license are recorded"]\nfor item in checks:\n    print("[ ]", item)` },
    quizzes: [quiz("摘要应该在什么时候最终定稿？", "When should the abstract be finalized?", [["正文完成并核对之后", "After the main text is complete and verified"], ["选题之前", "Before choosing a topic"], ["运行代码之前", "Before running code"]], 0, "摘要必须准确反映最终方法和结果。", "The abstract must accurately reflect the final method and results."), quiz("Draft Paper在本课程中的定位是什么？", "What is the role of the Draft Paper in this course?", [["可继续修改的研究初稿", "A research draft ready for further revision"], ["保证正式发表的论文", "A guaranteed publication"], ["只展示代码的附件", "An appendix that only shows code"]], 0, "正式文献综述、实验强化和投稿准备属于后续AI论文课。", "Formal literature review, stronger experiments, and submission preparation belong to the follow-on paper course.")],
    stage: pair("论文交接准备 2/2", "Paper Handoff Preparation 2/2"), kaggleAction: pair("在论文中加入Dataset和Notebook链接、许可证与访问日期。", "Add dataset and notebook links, license, and access date to the paper."), paperSection: pair("形成完整Draft Paper v1。", "Produce a complete Draft Paper v1."), line: pair("初稿不需要完美，但每一句都必须能追溯到证据。", "A draft need not be perfect, but every statement must trace to evidence."),
  },
  "15": {
    title: pair("Stage 4：Draft Paper展示与AI论文课衔接", "Stage 4: Draft Paper Presentation and AI Paper Handoff"),
    subtitle: pair("完成Python项目闭环，并明确下一门课程的修改任务", "Close the Python project and define the next course's revision work"),
    output: pair("提交可运行Notebook、Draft Paper v2、5–8页PPT和论文课程修改清单。", "Submit a runnable notebook, Draft Paper v2, a 5–8 slide deck, and a paper-course revision plan."),
    skills: [pair("展示研究证据", "Present research evidence"), pair("回应问题与限制", "Answer questions and state limits")],
    concepts: [[pair("Research story", "Research story"), pair("问题、数据、方法、发现和限制形成一条清楚主线。", "Question, data, method, finding, and limitation form one clear line.")], [pair("Handoff plan", "Handoff plan"), pair("把反馈变成后续AI论文课可以执行的修改任务。", "Turns feedback into revision tasks for the follow-on AI paper course.")]],
    vocab: [[pair("Takeaway", "Takeaway"), pair("希望听众记住的一句核心结论。", "The one core message the audience should remember.")], [pair("Revision", "Revision"), pair("根据证据和反馈对研究进行有目的的修改。", "A purposeful change based on evidence and feedback.")]],
    syntax: `final_package = {"kaggle_notebook":"runnable", "clean_data":"included", "draft_paper":"v2", "slides":"5–8", "revision_plan":"ready"}\nfor item, status in final_package.items():\n    print(item, status)`,
    demo: `handoff = {"literature_review":"expand in AI Paper course", "experiment":"review feature choices", "writing":"revise claims and citations", "submission":"not promised; evaluate after revision"}\nprint(handoff)`,
    lab: { title: pair("Five-Minute Research Story", "Five-Minute Research Story"), intro: pair("用问题、数据、方法、结果、限制和下一步完成展示。", "Present the question, data, method, result, limitation, and next step."), code: `talk_order = ["Question", "Kaggle dataset and license", "Python workflow", "Baseline vs linear MAE", "Key figure", "Limitation", "Next course plan"]\nfor item in talk_order:\n    print(item)` },
    project: { title: pair("Stage 4 Final Gate", "Stage 4 Final Gate"), input: pair("Notebook、清洁数据、论文初稿、PPT和教师反馈。", "Notebook, clean data, paper draft, slides, and instructor feedback."), process: pair("计时展示、核对交付物、记录反馈并制定修改优先级。", "Deliver a timed presentation, verify deliverables, record feedback, and prioritize revisions."), output: pair("Python课程最终成果包和AI论文课交接单。", "Final Python-course package and AI-paper-course handoff."), code: `priorities = ["must fix before next course", "should improve", "optional extension"]\nfor priority in priorities:\n    print(priority)` },
    quizzes: [quiz("无法回答一个问题时应该怎么做？", "What should a student do when unable to answer a question?", [["说明不确定性和验证方法", "State the uncertainty and how it could be tested"], ["编造答案", "Invent an answer"], ["回避所有问答", "Avoid all questions"]], 0, "研究交流允许不确定，但不允许伪造。", "Research communication allows uncertainty, not fabrication."), quiz("下一门AI论文课的重点是什么？", "What is the focus of the follow-on AI paper course?", [["文献、实验、引用和多轮修改", "Literature, experiments, citations, and iterative revision"], ["重新学习print", "Relearn print"], ["保证论文发表", "Guarantee publication"]], 0, "是否适合投稿要在后续修改后再评估。", "Publication suitability should be evaluated only after further revision.")],
    stage: pair("STAGE 4 / 4", "STAGE 4 / 4"), kaggleAction: pair("提交最终Notebook链接和可复现说明。", "Submit the final notebook link and reproducibility note."), paperSection: pair("完成Draft Paper v2并生成后续课程修改清单。", "Complete Draft Paper v2 and a revision list for the next course."), line: pair("Python课程交付的是可信初稿；论文课程负责把它继续打磨。", "The Python course delivers a credible draft; the paper course develops it further."),
  },
};

const pick = (value, lang) => value && value[lang] !== undefined ? value[lang] : value;
const localizePairs = (items, lang) => items.map(([a, b]) => [pick(a, lang), pick(b, lang)]);

function localizeLesson(no, lang) {
  const source = lessons[no];
  const stageSource = stageReviews[no] || null;
  const lessonType = stageSource ? "stage" : "knowledge";
  const mistakes = localizePairs(source.mistakes || commonMistakes, lang);
  const homework = (source.homework || [
    pair("完成本节核心任务并保存Notebook版本", "Complete the core task and save a notebook version"),
    pair("把代码应用到自己的Kaggle项目", "Apply the code to the selected Kaggle project"),
    pair("写3–5句结果或过程说明", "Write a 3–5 sentence result or process note"),
    pair("提交可访问的Notebook链接", "Submit an accessible notebook link"),
  ]).map((item) => pick(item, lang));
  const quizValue = (value) => [pick(value.q, lang), value.options.map((option) => pick(option, lang)), value.correct, pick(value.explain, lang)];
  const localizedStage = stageSource ? {
    number: stageSource.number,
    goal: pick(stageSource.goal, lang),
    materials: pick(stageSource.materials, lang),
    criteria: pick(stageSource.criteria, lang),
    questions: pick(stageSource.questions, lang),
    risks: pick(stageSource.risks, lang),
    nextGate: pick(stageSource.nextGate, lang),
  } : null;
  return {
    classNo: no,
    lessonType,
    stageNumber: stageSource ? stageSource.number : null,
    title: pick(source.title, lang),
    subtitle: pick(source.subtitle, lang),
    duration: 120,
    output: pick(source.output, lang),
    objectives: source.skills.map((item) => pick(item, lang)),
    skills: source.skills.map((item) => pick(item, lang)),
    concepts: localizePairs(source.concepts, lang),
    vocab: localizePairs(source.vocab, lang),
    syntax: source.syntax,
    demo: source.demo,
    labTitle: pick(source.lab.title, lang),
    labIntro: pick(source.lab.intro, lang),
    labCode: source.lab.code,
    labRuntime: "browser",
    requiredPackages: browserPackagesByLesson[no],
    projectTitle: pick(source.project.title, lang),
    projectInput: pick(source.project.input, lang),
    projectProcess: pick(source.project.process, lang),
    projectOutput: pick(source.project.output, lang),
    projectCode: source.project.code,
    projectRuntime: "kaggle",
    starterCode: source.project.code,
    quiz1: quizValue(source.quizzes[0]),
    quiz2: quizValue(source.quizzes[1]),
    mistakes,
    homework,
    line: pick(source.line, lang),
    stage: pick(source.stage, lang),
    kaggleAction: pick(source.kaggleAction, lang),
    projectAction: pick(source.kaggleAction, lang),
    paperSection: pick(source.paperSection, lang),
    paperEvidence: pick(source.paperSection, lang),
    teacherNotes: lang === "zh" ? "先检查学生能否解释输入、处理和输出，再给修改建议。" : "Check whether the student can explain input, process, and output before giving revision advice.",
    challenge: lang === "zh" ? "仅在核心任务完成后增加一个小检查或一张图；不得改变任务类型。" : "Only after the core task, add one small check or figure; do not change the task type.",
    rubric: lang === "zh" ? ["能运行", "能解释", "证据可追溯", "Notebook结构清楚"] : ["Runs", "Can be explained", "Evidence is traceable", "Notebook is organized"],
    slides: slideSchema[lessonType].map((slide) => ({ id: slide.id, type: slide.type, content: pick(slide.content, lang) })),
    stageReview: localizedStage,
  };
}

const zh = {};
const en = {};
Object.keys(lessons).forEach((no) => {
  zh[no] = localizeLesson(no, "zh");
  en[no] = localizeLesson(no, "en");
});

const catalog = {
  zh: Object.values(zh).sort((a, b) => Number(a.classNo) - Number(b.classNo)).map((lesson) => ({
    id: `lesson-${lesson.classNo}`,
    n: Number(lesson.classNo),
    title: lesson.title,
    summary: `${lesson.stage} · ${lesson.output}`,
    tags: [`Class ${lesson.classNo}`, lesson.stage, "Kaggle", Number(lesson.classNo) >= 13 ? "Draft Paper" : "Python Project"],
    duration: "120 minutes",
    status: "ready",
  })),
  en: Object.values(en).sort((a, b) => Number(a.classNo) - Number(b.classNo)).map((lesson) => ({
    id: `lesson-${lesson.classNo}`,
    n: Number(lesson.classNo),
    title: lesson.title,
    summary: `${lesson.stage} · ${lesson.output}`,
    tags: [`Class ${lesson.classNo}`, lesson.stage, "Kaggle", Number(lesson.classNo) >= 13 ? "Draft Paper" : "Python Project"],
    duration: "120 minutes",
    status: "ready",
  })),
};

const regressionPolicy = {
  split: "train_test_split(..., test_size=0.20, random_state=42)",
  baseline: 'DummyRegressor(strategy="mean")',
  model: "LinearRegression",
  metric: "mean_absolute_error",
  interpretation: "Lower MAE is better; coefficients are associations in this fitted model, not causal effects.",
  leakageRules: [
    "The test set is not used for training, feature choice, cleaning decisions, or target imputation.",
    "Prefer a small set of numeric features. Any categorical preprocessing uses one instructor-provided pipeline.",
  ],
};

const whitelist = [
  {
    datasetTitle: "Student Performance (Multiple Linear Regression)",
    kaggleUrl: "https://www.kaggle.com/datasets/nikhil7280/student-performance-multiple-linear-regression",
    publisherAuthor: "Nikhil Narayan",
    originalSource: "Synthetic dataset created for illustrative purposes, according to the dataset page.",
    license: "Other - free to share and use per dataset description",
    accessDate: "2026-07-16",
    verificationDate: "2026-07-16",
    fileName: null,
    fileSize: null,
    rows: 10000,
    columns: 6,
    target: "Performance Index",
    allowedFeatures: ["Hours Studied", "Previous Scores", "Sleep Hours", "Sample Question Papers Practiced"],
    excludedFeatures: ["Extracurricular Activities (excluded from the core path unless the instructor applies the fixed categorical preprocessing)"],
    missingSummary: null,
    privacyEthics: "Synthetic; do not present fitted relationships as evidence about real students or as causal findings.",
    highSchoolSuitability: "Beginner tabular regression with a continuous target and mostly numeric features.",
    verificationStatus: "pending manual review",
    unknownFields: ["exact CSV file name", "file size", "missing-value summary"],
  },
  {
    datasetTitle: "Student Academic Performance Dataset",
    kaggleUrl: "https://www.kaggle.com/datasets/aryancodes12fyds/student-academic-performance-dataset",
    publisherAuthor: null,
    originalSource: "Synthetic dataset created with statistical modeling, according to the dataset page.",
    license: "CC0 Public Domain",
    accessDate: "2026-07-16",
    verificationDate: "2026-07-16",
    fileName: "student_academic_performance.csv",
    fileSize: "16.64 kB dataset version; exact CSV size not separately confirmed",
    rows: 250,
    columns: 12,
    target: "GPA",
    allowedFeatures: ["Instructor-selected numeric study, sleep, attendance, stress, and social-media fields after exact column-name review"],
    excludedFeatures: ["Any identifier field", "Any field not confirmed on the downloaded CSV"],
    missingSummary: "Dataset page states no missing values; recheck the downloaded CSV before class.",
    privacyEthics: "Synthetic and described as containing no real student data; avoid real-student causal or intervention claims.",
    highSchoolSuitability: "Small, mostly numeric table suitable for EDA and introductory regression.",
    verificationStatus: "pending manual review",
    unknownFields: ["display name of publisher/author", "exact allowed column names", "exact CSV file size"],
  },
  {
    datasetTitle: "Energy Consumption Dataset - Linear Regression",
    kaggleUrl: "https://www.kaggle.com/datasets/govindaramsriram/energy-consumption-dataset-linear-regression",
    publisherAuthor: "GOVINDARAM SRIRAM",
    originalSource: null,
    license: "CC BY 4.0",
    accessDate: "2026-07-16",
    verificationDate: "2026-07-16",
    fileName: null,
    fileSize: null,
    rows: null,
    columns: null,
    target: "Energy Consumption",
    allowedFeatures: ["Instructor-confirmed numeric building area, occupants, appliances, and temperature fields"],
    excludedFeatures: ["Building type and day-of-week categories unless the instructor applies the fixed categorical preprocessing"],
    missingSummary: null,
    privacyEthics: "Building and environmental data; confirm provenance and whether the records are synthetic before making real-world claims.",
    highSchoolSuitability: "Clear continuous-target regression topic, subject to a final size and field audit.",
    verificationStatus: "pending manual review",
    unknownFields: ["original source/provenance", "CSV file name", "file size", "row count", "column count", "missing-value summary"],
  },
  {
    datasetTitle: "Study Hours and Student Scores for Linear Regression",
    kaggleUrl: "https://www.kaggle.com/datasets/douaabennoune/study-hours-student-scores-for-linear-regression",
    publisherAuthor: "douaa bennoune",
    originalSource: "100 randomly generated study-hours and score records, according to the dataset page.",
    license: "CC0 Public Domain",
    accessDate: "2026-07-16",
    verificationDate: "2026-07-16",
    fileName: null,
    fileSize: null,
    rows: 100,
    columns: 2,
    target: "Scores",
    allowedFeatures: ["Hours"],
    excludedFeatures: [],
    missingSummary: null,
    privacyEthics: "Randomly generated; suitable only for learning the workflow, not for claims about real students.",
    highSchoolSuitability: "Simplest fallback regression path with one numeric feature and one numeric target.",
    verificationStatus: "pending manual review",
    unknownFields: ["exact CSV file name", "file size", "missing-value summary"],
  },
];

module.exports = { zh, en, catalog, whitelist, regressionPolicy, slideSchema };
